views:
  - name: ltv_view
    description: This metric calculates the LTV
    public: true
    meta:
      title: User Engagement
      tags:   
        - DPDomain.LTV
        - DPUsecase.LTV
      
      metric:          #mandatory
        expression: "30 6 L * *"
        timezone: "UTC"
        window: "day"

          
    tables:
      - join_path: copy_visit_ltv
        prefix: true
        includes:
          - ltv  #MEasure       
          - profit #MEasure
          - total_unique_ids #measure
          - Visit_id   #Groupby column
          - visit_datetime # Timestamp-mandatory
