views:
  - name: revenue_view
    description: This metric calculates the average revenue per visit  
    public: true
    meta:
      title: User Engagement
      tags:   
        - DPDomain.LTV
        - DPUsecase.LTV
      
      metric:          #mandatory
        expression: "30 6 L * *"
        timezone: "UTC"
        window: "day"

    tables:
      - join_path: copy_visit_ltv
        prefix: true
        includes:
           - avg_revenue_per_visit
           - calc_revenue
           - total_visits
           - device
           - entry_channel
           - Visit_id
           - visit_datetime